[build-system]
requires = ["setuptools>=64", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "fireredasr2s"
version = "0.0.1"
description = "Industrial-grade ASR system with VAD, LID, and punctuation prediction"
readme = "README.md"
license = "Apache-2.0"
requires-python = ">=3.11"
dependencies = [
    "torch==2.10.0",
    "torchaudio==2.10.0",
    "transformers==5.1.0",
    "fastapi==0.139.0",
    "uvicorn[standard]==0.51.0",
    "numpy>=2.4.2,<3.0.0",
    "cn2an>=0.5.23",
    "kaldiio>=2.18.1",
    "sentencepiece>=0.2.1",
    "soundfile>=0.13.1",
    "textgrid>=1.6.1",
    "kaldi-native-fbank>=1.22.3",
    "onnx>=1.22.0",
    "onnxruntime>=1.27.0",
    "PyYAML>=6.0.2",
    "pytest>=9.1.1",
    "httpx2==2.7.0",
]

[project.scripts]
fireredasr2s-cli = "fireredasr2s.fireredasr2s_cli:cli_main"
fireredlid-server = "fireredasr2s.fireredlid.server:main"

[tool.setuptools.packages.find]
include = ["fireredasr2s*"]

[tool.uv.sources]
torch = [
    { index = "pytorch-cu130", marker = "sys_platform == 'linux' and platform_machine == 'x86_64'" },
]
torchaudio = [
    { index = "pytorch-cu130", marker = "sys_platform == 'linux' and platform_machine == 'x86_64'" },
]

[[tool.uv.index]]
name = "pytorch-cu130"
url = "https://download.pytorch.org/whl/cu130"
explicit = true
